language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t djulbicb/test_app -f Dockerfile.dev .

script:
  - docker run -e CI=true djulbicb/test_app npm run test -- --coverage
